version: '3.1'

services:

  web:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - node-app-a
      - node-app-b
      - node-app-catch-all

  node-app-catch-all:
    build: ./node-app
    restart: always
    environment:
      CATCH_ALL: 'true'
      PORT: 8000

  node-app-a:
    build: ./node-app
    restart: always
    environment:
      ID: a
      PORT: 8000

  node-app-b:
    build: ./node-app
    restart: always
    environment:
      ID: b
      PORT: 8000